# Generated by Django 6.0 on 2026-04-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('article', models.TextField()),
                ('article_audio', models.CharField(blank=True, db_column='article_audio', max_length=500, null=True)),
                ('conversation_audio', models.CharField(blank=True, db_column='conversation_audio', max_length=500, null=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('main_topic', models.CharField(db_column='main_topic', max_length=100)),
                ('negative_conversation', models.TextField(blank=True, db_column='negative_conversation', null=True)),
                ('positive_conversation', models.TextField(blank=True, db_column='positive_conversation', null=True)),
                ('sub_topic', models.CharField(db_column='sub_topic', max_length=200)),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
            ],
            options={
                'db_table': 'knowledge_base',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('description', models.TextField(blank=True, null=True)),
                ('dosage_instructions', models.TextField(blank=True, db_column='dosage_instructions', null=True)),
                ('expiry_date', models.DateField(db_column='expiry_date')),
                ('last_updated', models.DateTimeField(db_column='last_updated')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacture_date', models.DateField(blank=True, db_column='manufacture_date', null=True)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'medicines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, db_column='created_at', null=True)),
                ('image_url', models.CharField(blank=True, db_column='image_url', max_length=500, null=True)),
                ('intro', models.CharField(blank=True, max_length=100, null=True)),
                ('main_topic', models.CharField(db_column='main_topic', max_length=200)),
                ('router_link', models.CharField(blank=True, db_column='router_link', max_length=200, null=True)),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_column='updated_at', null=True)),
            ],
            options={
                'db_table': 'roadmaps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('email', models.CharField(max_length=254)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=100)),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YogaPose',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('yoga_name', models.CharField(db_column='yoga_name', max_length=255)),
                ('blog_content', models.CharField(blank=True, db_column='blog_content', max_length=10000, null=True)),
                ('audio_url', models.CharField(blank=True, db_column='audio_url', max_length=1000, null=True)),
                ('video_url', models.CharField(blank=True, db_column='video_url', max_length=1000, null=True)),
                ('image_url', models.CharField(blank=True, db_column='image_url', max_length=1000, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'yoga_poses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Backlog', 'Backlog'), ('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='To Do', max_length=20)),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='api.tag')),
            ],
        ),
    ]
