# Generated by Django 6.0 on 2026-04-06 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_epic_remove_task_tags_task_epic_delete_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.epic'),
        ),
    ]
