# Generated by Django 6.0 on 2026-04-06 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_epic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], default='viewer', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.epic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Epic Access',
                'verbose_name_plural': 'Epic Accesses',
                'unique_together': {('epic', 'user')},
            },
        ),
    ]
