# Generated by Django 6.0 on 2026-04-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fruits_gallery',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FruitGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=1000)),
                ('fruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fruits.fruitgallery')),
            ],
            options={
                'db_table': 'fruits_gallery_images',
                'ordering': ['id'],
            },
        ),
    ]
